export const ADDTOCART = 'ADDTOCART'
export const REMOVEFROMCART = 'REMOVEFROMCART'
export const DELETEALLITEMS = 'DELETEALLITEMS'
export const OPEN = 'OPEN'
export const USER = 'USER'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const DELETEINDIVIDUAL = 'DELETEINDIVIDUAL'